// Code generated by tools/forever/gen_spell_tuning.py. DO NOT EDIT.

package core

var ForeverSpellTunings = map[int32]ForeverSpellTuning{
	10:    {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	116:   {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0, TickCoeff: 0},       // Frostbolt
	120:   {DirectScale: 0.9717, DotScale: 0.9717, DirectCoeff: 0.0, TickCoeff: 0.0},   // Cone of Cold
	122:   {DirectScale: 0.9742, DotScale: 0.9742, DirectCoeff: 0, TickCoeff: 0},       // Frost Nova
	133:   {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 0, TickCoeff: 0},       // Fireball
	143:   {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 0, TickCoeff: 0},       // Fireball
	145:   {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 0, TickCoeff: 0},       // Fireball
	172:   {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0, TickCoeff: 0},       // Corruption
	205:   {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0, TickCoeff: 0},       // Frostbolt
	339:   {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0, TickCoeff: 0},       // Entangling Roots
	348:   {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0, TickCoeff: 0},       // Immolate
	403:   {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0, TickCoeff: 0},       // Lightning Bolt
	421:   {DirectScale: 0.2357, DotScale: 0.2357, DirectCoeff: 0.571, TickCoeff: 0.0}, // Chain Lightning
	529:   {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0, TickCoeff: 0},       // Lightning Bolt
	548:   {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0, TickCoeff: 0},       // Lightning Bolt
	585:   {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0, TickCoeff: 0},       // Smite
	589:   {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0, TickCoeff: 0},       // Shadow Word: Pain
	591:   {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0, TickCoeff: 0},       // Smite
	594:   {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0, TickCoeff: 0},       // Shadow Word: Pain
	598:   {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0, TickCoeff: 0},       // Smite
	603:   {DirectScale: 0.5444, DotScale: 0.5444, DirectCoeff: 0.0, TickCoeff: 0.0},   // Curse of Doom
	686:   {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0, TickCoeff: 0},       // Shadow Bolt
	689:   {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0, TickCoeff: 0},       // Drain Life
	695:   {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0, TickCoeff: 0},       // Shadow Bolt
	699:   {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0.0, TickCoeff: 0.1},   // Drain Life
	705:   {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0, TickCoeff: 0},       // Shadow Bolt
	707:   {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0, TickCoeff: 0},       // Immolate
	709:   {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0.0, TickCoeff: 0.1},   // Drain Life
	837:   {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0, TickCoeff: 0},       // Frostbolt
	865:   {DirectScale: 0.9742, DotScale: 0.9742, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Nova
	879:   {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	915:   {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	930:   {DirectScale: 0.2357, DotScale: 0.2357, DirectCoeff: 0.571, TickCoeff: 0.0}, // Chain Lightning
	943:   {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	970:   {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0, TickCoeff: 0},       // Shadow Word: Pain
	980:   {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0, TickCoeff: 0},       // Curse of Agony
	984:   {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0.0, TickCoeff: 0.0},   // Smite
	992:   {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	1004:  {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0.0, TickCoeff: 0.0},   // Smite
	1014:  {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0, TickCoeff: 0},       // Curse of Agony
	1062:  {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0, TickCoeff: 0},       // Entangling Roots
	1079:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	1088:  {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	1094:  {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	1106:  {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	1120:  {DirectScale: 0.9231, DotScale: 0.9231, DirectCoeff: 0, TickCoeff: 0},       // Drain Soul
	1449:  {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0, TickCoeff: 0},       // Arcane Explosion
	1510:  {DirectScale: 1.4000, DotScale: 1.4000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Volley
	1822:  {DirectScale: 1.0517, DotScale: 1.0625, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rake
	1823:  {DirectScale: 1.0517, DotScale: 1.0625, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rake
	1824:  {DirectScale: 1.0517, DotScale: 1.0625, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rake
	1943:  {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	1949:  {DirectScale: 0.9859, DotScale: 0.9859, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hellfire
	1978:  {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0, TickCoeff: 0},       // Serpent Sting
	2098:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0, TickCoeff: 0},       // Eviscerate
	2120:  {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0, TickCoeff: 0},       // Flamestrike
	2121:  {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Flamestrike
	2136:  {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0, TickCoeff: 0},       // Fire Blast
	2137:  {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0, TickCoeff: 0},       // Fire Blast
	2138:  {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0.429, TickCoeff: 0.0}, // Fire Blast
	2767:  {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	2860:  {DirectScale: 0.2357, DotScale: 0.2357, DirectCoeff: 0.571, TickCoeff: 0.0}, // Chain Lightning
	2912:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	2941:  {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	2944:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	2948:  {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	3044:  {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0, TickCoeff: 0},       // Arcane Shot
	3140:  {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 0, TickCoeff: 0},       // Fireball
	5143:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0, TickCoeff: 0},       // Arcane Missiles
	5144:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0, TickCoeff: 0},       // Arcane Missiles
	5145:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	5176:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0, TickCoeff: 0},       // Wrath
	5177:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0, TickCoeff: 0},       // Wrath
	5178:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0, TickCoeff: 0},       // Wrath
	5179:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0.571, TickCoeff: 0.0}, // Wrath
	5180:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0.571, TickCoeff: 0.0}, // Wrath
	5195:  {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	5196:  {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	5570:  {DirectScale: 0.5741, DotScale: 0.5741, DirectCoeff: 0.0, TickCoeff: 0.158}, // Insect Swarm
	5614:  {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	5615:  {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	5676:  {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0, TickCoeff: 0},       // Searing Pain
	5740:  {DirectScale: 0.9693, DotScale: 0.9693, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rain of Fire
	6041:  {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	6060:  {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0.0, TickCoeff: 0.0},   // Smite
	6131:  {DirectScale: 0.9742, DotScale: 0.9742, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Nova
	6141:  {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	6217:  {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0.0, TickCoeff: 0.133}, // Curse of Agony
	6219:  {DirectScale: 0.9693, DotScale: 0.9693, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rain of Fire
	6222:  {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0, TickCoeff: 0},       // Corruption
	6223:  {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0.0, TickCoeff: 0.2},   // Corruption
	6353:  {DirectScale: 0.5451, DotScale: 0.5451, DirectCoeff: 0.0, TickCoeff: 0.0},   // Soul Fire
	6572:  {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0, TickCoeff: 0},       // Revenge
	6574:  {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Revenge
	6760:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0, TickCoeff: 0},       // Eviscerate
	6761:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0, TickCoeff: 0},       // Eviscerate
	6762:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
	6780:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0.571, TickCoeff: 0.0}, // Wrath
	6789:  {DirectScale: 0.9664, DotScale: 0.9664, DirectCoeff: 0.0, TickCoeff: 0.0},   // Death Coil
	7269:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0, TickCoeff: 0},       // Arcane Missiles
	7270:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	7294:  {DirectScale: 1.5000, DotScale: 1.5000, DirectCoeff: 0, TickCoeff: 0},       // Retribution Aura
	7322:  {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	7379:  {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Revenge
	7641:  {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	7648:  {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0.0, TickCoeff: 0.2},   // Corruption
	7651:  {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0.0, TickCoeff: 0.1},   // Drain Life
	8033:  {DirectScale: 0.9037, DotScale: 0.9037, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frostbrand Weapon
	8038:  {DirectScale: 0.9037, DotScale: 0.9037, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frostbrand Weapon
	8042:  {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0, TickCoeff: 0},       // Earth Shock
	8044:  {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0, TickCoeff: 0},       // Earth Shock
	8045:  {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0, TickCoeff: 0},       // Earth Shock
	8046:  {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0.0, TickCoeff: 0.0},   // Earth Shock
	8050:  {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0, TickCoeff: 0},       // Flame Shock
	8052:  {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0, TickCoeff: 0},       // Flame Shock
	8053:  {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0.214, TickCoeff: 0.1}, // Flame Shock
	8056:  {DirectScale: 0.5672, DotScale: 0.5672, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Shock
	8058:  {DirectScale: 0.5672, DotScale: 0.5672, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Shock
	8092:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0, TickCoeff: 0},       // Mind Blast
	8102:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0, TickCoeff: 0},       // Mind Blast
	8103:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	8104:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	8105:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	8106:  {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	8187:  {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	8190:  {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	8288:  {DirectScale: 0.9231, DotScale: 0.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Drain Soul
	8289:  {DirectScale: 0.9231, DotScale: 0.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Drain Soul
	8400:  {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	8401:  {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	8402:  {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	8406:  {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	8407:  {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	8408:  {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	8412:  {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0.429, TickCoeff: 0.0}, // Fire Blast
	8413:  {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0.429, TickCoeff: 0.0}, // Fire Blast
	8416:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	8417:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	8418:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	8419:  {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	8422:  {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Flamestrike
	8423:  {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Flamestrike
	8427:  {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	8437:  {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Explosion
	8438:  {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Explosion
	8439:  {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Explosion
	8444:  {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	8445:  {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	8446:  {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	8492:  {DirectScale: 0.9717, DotScale: 0.9717, DirectCoeff: 0.0, TickCoeff: 0.0},   // Cone of Cold
	8623:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
	8624:  {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
	8639:  {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	8640:  {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	8905:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0.571, TickCoeff: 0.0}, // Wrath
	8921:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0, TickCoeff: 0},       // Moonfire
	8924:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0, TickCoeff: 0},       // Moonfire
	8925:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0, TickCoeff: 0},       // Moonfire
	8926:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	8927:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	8928:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	8929:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	8949:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	8950:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	8951:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	9492:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	9493:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	9752:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	9833:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	9834:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	9835:  {DirectScale: 0.6585, DotScale: 0.6250, DirectCoeff: 0.15, TickCoeff: 0.13}, // Moonfire
	9852:  {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	9853:  {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	9875:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	9876:  {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	9894:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	9896:  {DirectScale: 0.9059, DotScale: 0.9059, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rip
	9904:  {DirectScale: 1.0517, DotScale: 1.0625, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rake
	9912:  {DirectScale: 0.3640, DotScale: 0.3640, DirectCoeff: 0.571, TickCoeff: 0.0}, // Wrath
	10148: {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	10149: {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	10150: {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	10151: {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	10159: {DirectScale: 0.9717, DotScale: 0.9717, DirectCoeff: 0.0, TickCoeff: 0.0},   // Cone of Cold
	10160: {DirectScale: 0.9717, DotScale: 0.9717, DirectCoeff: 0.0, TickCoeff: 0.0},   // Cone of Cold
	10161: {DirectScale: 0.9717, DotScale: 0.9717, DirectCoeff: 0.0, TickCoeff: 0.0},   // Cone of Cold
	10179: {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	10180: {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	10181: {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	10185: {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	10186: {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	10187: {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	10197: {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0.429, TickCoeff: 0.0}, // Fire Blast
	10199: {DirectScale: 0.9340, DotScale: 0.9340, DirectCoeff: 0.429, TickCoeff: 0.0}, // Fire Blast
	10201: {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Explosion
	10202: {DirectScale: 0.9576, DotScale: 0.9576, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Explosion
	10205: {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	10206: {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	10207: {DirectScale: 0.7021, DotScale: 0.7021, DirectCoeff: 0.429, TickCoeff: 0.0}, // Scorch
	10211: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	10212: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	10215: {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Flamestrike
	10216: {DirectScale: 1.0012, DotScale: 0.9765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Flamestrike
	10230: {DirectScale: 0.9742, DotScale: 0.9742, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Nova
	10273: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	10274: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	10298: {DirectScale: 1.5000, DotScale: 1.5000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Retribution Aura
	10299: {DirectScale: 1.5000, DotScale: 1.5000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Retribution Aura
	10300: {DirectScale: 1.5000, DotScale: 1.5000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Retribution Aura
	10301: {DirectScale: 1.5000, DotScale: 1.5000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Retribution Aura
	10312: {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	10313: {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	10314: {DirectScale: 0.9401, DotScale: 0.9401, DirectCoeff: 0.0, TickCoeff: 0.0},   // Exorcism
	10391: {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	10392: {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	10412: {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0.0, TickCoeff: 0.0},   // Earth Shock
	10413: {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0.0, TickCoeff: 0.0},   // Earth Shock
	10414: {DirectScale: 0.5669, DotScale: 0.5669, DirectCoeff: 0.0, TickCoeff: 0.0},   // Earth Shock
	10447: {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0.214, TickCoeff: 0.1}, // Flame Shock
	10448: {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0.214, TickCoeff: 0.1}, // Flame Shock
	10456: {DirectScale: 0.9037, DotScale: 0.9037, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frostbrand Weapon
	10472: {DirectScale: 0.5672, DotScale: 0.5672, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Shock
	10473: {DirectScale: 0.5672, DotScale: 0.5672, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frost Shock
	10579: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10580: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10581: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10585: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10586: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10587: {DirectScale: 0.9733, DotScale: 0.9733, DirectCoeff: 0.0, TickCoeff: 0.0},   // Magma Totem
	10605: {DirectScale: 0.2357, DotScale: 0.2357, DirectCoeff: 0.571, TickCoeff: 0.0}, // Chain Lightning
	10797: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0, TickCoeff: 0},       // Starshards
	10892: {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	10893: {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	10894: {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	10933: {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0.0, TickCoeff: 0.0},   // Smite
	10934: {DirectScale: 0.4326, DotScale: 0.4326, DirectCoeff: 0.0, TickCoeff: 0.0},   // Smite
	10945: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	10946: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	10947: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.429, TickCoeff: 0.0}, // Mind Blast
	11113: {DirectScale: 0.9801, DotScale: 0.9801, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blast Wave
	11273: {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	11274: {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	11275: {DirectScale: 0.5863, DotScale: 0.5863, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rupture
	11299: {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
	11300: {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
	11337: {DirectScale: 0.6769, DotScale: 0.6769, DirectCoeff: 0.0, TickCoeff: 0.0},   // Instant Poison VI
	11340: {DirectScale: 0.6769, DotScale: 0.6769, DirectCoeff: 0.0, TickCoeff: 0.0},   // Instant Poison VI
	11366: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	11600: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Revenge
	11601: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Revenge
	11659: {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	11660: {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	11661: {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	11665: {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	11667: {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	11668: {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	11671: {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0.0, TickCoeff: 0.2},   // Corruption
	11672: {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0.0, TickCoeff: 0.2},   // Corruption
	11675: {DirectScale: 0.9231, DotScale: 0.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Drain Soul
	11677: {DirectScale: 0.9693, DotScale: 0.9693, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rain of Fire
	11678: {DirectScale: 0.9693, DotScale: 0.9693, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rain of Fire
	11683: {DirectScale: 0.9859, DotScale: 0.9859, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hellfire
	11684: {DirectScale: 0.9859, DotScale: 0.9859, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hellfire
	11699: {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0.0, TickCoeff: 0.1},   // Drain Life
	11700: {DirectScale: 0.7183, DotScale: 0.7183, DirectCoeff: 0.0, TickCoeff: 0.1},   // Drain Life
	11711: {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0.0, TickCoeff: 0.133}, // Curse of Agony
	11712: {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0.0, TickCoeff: 0.133}, // Curse of Agony
	11713: {DirectScale: 0.5287, DotScale: 0.5287, DirectCoeff: 0.0, TickCoeff: 0.133}, // Curse of Agony
	12505: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	12522: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	12523: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	12524: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	12525: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	12526: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	13018: {DirectScale: 0.9801, DotScale: 0.9801, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blast Wave
	13019: {DirectScale: 0.9801, DotScale: 0.9801, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blast Wave
	13020: {DirectScale: 0.9801, DotScale: 0.9801, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blast Wave
	13021: {DirectScale: 0.9801, DotScale: 0.9801, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blast Wave
	13549: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0, TickCoeff: 0},       // Serpent Sting
	13550: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0, TickCoeff: 0},       // Serpent Sting
	13551: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	13552: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	13553: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	13554: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	13555: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	14281: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0, TickCoeff: 0},       // Arcane Shot
	14282: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14283: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14284: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14285: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14286: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14287: {DirectScale: 1.1858, DotScale: 1.1858, DirectCoeff: 0.0, TickCoeff: 0.0},   // Arcane Shot
	14294: {DirectScale: 1.4000, DotScale: 1.4000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Volley
	14295: {DirectScale: 1.4000, DotScale: 1.4000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Volley
	14914: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15207: {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	15208: {DirectScale: 0.4431, DotScale: 0.4431, DirectCoeff: 0.714, TickCoeff: 0.0}, // Lightning Bolt
	15237: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	15261: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15262: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15263: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15264: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15265: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15266: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15267: {DirectScale: 0.5174, DotScale: 0.5172, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Fire
	15407: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	15430: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	15431: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	16355: {DirectScale: 0.9037, DotScale: 0.9037, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frostbrand Weapon
	16356: {DirectScale: 0.9037, DotScale: 0.9037, DirectCoeff: 0.0, TickCoeff: 0.0},   // Frostbrand Weapon
	16914: {DirectScale: 0.9851, DotScale: 0.9851, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hurricane
	17311: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	17312: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	17313: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	17314: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	17401: {DirectScale: 0.9851, DotScale: 0.9851, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hurricane
	17402: {DirectScale: 0.9851, DotScale: 0.9851, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hurricane
	17877: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	17919: {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0.0, TickCoeff: 0.0},   // Searing Pain
	17920: {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0.0, TickCoeff: 0.0},   // Searing Pain
	17921: {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0.0, TickCoeff: 0.0},   // Searing Pain
	17922: {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0.0, TickCoeff: 0.0},   // Searing Pain
	17923: {DirectScale: 0.5155, DotScale: 0.5155, DirectCoeff: 0.0, TickCoeff: 0.0},   // Searing Pain
	17924: {DirectScale: 0.5451, DotScale: 0.5451, DirectCoeff: 0.0, TickCoeff: 0.0},   // Soul Fire
	17925: {DirectScale: 0.9664, DotScale: 0.9664, DirectCoeff: 0.0, TickCoeff: 0.0},   // Death Coil
	17926: {DirectScale: 0.9664, DotScale: 0.9664, DirectCoeff: 0.0, TickCoeff: 0.0},   // Death Coil
	17962: {DirectScale: 0.5618, DotScale: 0.5618, DirectCoeff: 0.429, TickCoeff: 0.0}, // Conflagrate
	18265: {DirectScale: 0.9111, DotScale: 0.9111, DirectCoeff: 0.0, TickCoeff: 0.05},  // Siphon Life
	18807: {DirectScale: 0.9155, DotScale: 0.9155, DirectCoeff: 0.0, TickCoeff: 0.167}, // Mind Flay
	18809: {DirectScale: 0.7260, DotScale: 0.7910, DirectCoeff: 1.0, TickCoeff: 0.0},   // Pyroblast
	18867: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	18868: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	18869: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	18870: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	18871: {DirectScale: 0.5605, DotScale: 0.5605, DirectCoeff: 0.0, TickCoeff: 0.0},   // Shadowburn
	18879: {DirectScale: 0.9111, DotScale: 0.9111, DirectCoeff: 0.0, TickCoeff: 0.05},  // Siphon Life
	18880: {DirectScale: 0.9111, DotScale: 0.9111, DirectCoeff: 0.0, TickCoeff: 0.05},  // Siphon Life
	18881: {DirectScale: 0.9111, DotScale: 0.9111, DirectCoeff: 0.0, TickCoeff: 0.05},  // Siphon Life
	18930: {DirectScale: 0.5618, DotScale: 0.5618, DirectCoeff: 0.429, TickCoeff: 0.0}, // Conflagrate
	18931: {DirectScale: 0.5618, DotScale: 0.5618, DirectCoeff: 0.429, TickCoeff: 0.0}, // Conflagrate
	18932: {DirectScale: 0.5618, DotScale: 0.5618, DirectCoeff: 0.429, TickCoeff: 0.0}, // Conflagrate
	19276: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	19277: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	19278: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	19279: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	19280: {DirectScale: 0.9381, DotScale: 0.9381, DirectCoeff: 0.0, TickCoeff: 0.1},   // Devouring Plague
	19296: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0, TickCoeff: 0},       // Starshards
	19299: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Starshards
	19302: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Starshards
	19303: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Starshards
	19304: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Starshards
	19305: {DirectScale: 1.9231, DotScale: 1.9231, DirectCoeff: 0.0, TickCoeff: 0.0},   // Starshards
	19474: {DirectScale: 0.9693, DotScale: 0.9693, DirectCoeff: 0.0, TickCoeff: 0.0},   // Rain of Fire
	19970: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	19971: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	19972: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	19973: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0.0, TickCoeff: 0.0},   // Entangling Roots
	19974: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0, TickCoeff: 0},       // Entangling Roots
	19975: {DirectScale: 0.8667, DotScale: 0.8667, DirectCoeff: 0, TickCoeff: 0},       // Entangling Roots
	20473: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	20925: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shield
	20927: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shield
	20928: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shield
	20929: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	20930: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	23455: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	23458: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	23459: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	24239: {DirectScale: 0.9396, DotScale: 0.9396, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hammer of Wrath
	24274: {DirectScale: 0.9396, DotScale: 0.9396, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hammer of Wrath
	24275: {DirectScale: 0.9396, DotScale: 0.9396, DirectCoeff: 0.0, TickCoeff: 0.0},   // Hammer of Wrath
	24974: {DirectScale: 0.5741, DotScale: 0.5741, DirectCoeff: 0.0, TickCoeff: 0.158}, // Insect Swarm
	24975: {DirectScale: 0.5741, DotScale: 0.5741, DirectCoeff: 0.0, TickCoeff: 0.158}, // Insect Swarm
	24976: {DirectScale: 0.5741, DotScale: 0.5741, DirectCoeff: 0.0, TickCoeff: 0.158}, // Insect Swarm
	24977: {DirectScale: 0.5741, DotScale: 0.5741, DirectCoeff: 0.0, TickCoeff: 0.158}, // Insect Swarm
	25288: {DirectScale: 1.7000, DotScale: 1.7000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Revenge
	25295: {DirectScale: 1.0000, DotScale: 1.0000, DirectCoeff: 0.0, TickCoeff: 0.0},   // Serpent Sting
	25298: {DirectScale: 0.7056, DotScale: 0.7056, DirectCoeff: 1.0, TickCoeff: 0.0},   // Starfire
	25304: {DirectScale: 0.8879, DotScale: 0.8879, DirectCoeff: 0.814, TickCoeff: 0.0}, // Frostbolt
	25306: {DirectScale: 0.7124, DotScale: 0.7895, DirectCoeff: 1.0, TickCoeff: 0.0},   // Fireball
	25307: {DirectScale: 0.5255, DotScale: 0.5255, DirectCoeff: 0.857, TickCoeff: 0.0}, // Shadow Bolt
	25309: {DirectScale: 0.5663, DotScale: 0.5392, DirectCoeff: 0.2, TickCoeff: 0.13},  // Immolate
	25311: {DirectScale: 0.5328, DotScale: 0.5328, DirectCoeff: 0.0, TickCoeff: 0.2},   // Corruption
	25345: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	25346: {DirectScale: 0.9087, DotScale: 0.9087, DirectCoeff: 0.0, TickCoeff: 0.2},   // Arcane Missiles
	25349: {DirectScale: 0.6765, DotScale: 0.6765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Deadly Poison V
	25351: {DirectScale: 0.6765, DotScale: 0.6765, DirectCoeff: 0.0, TickCoeff: 0.0},   // Deadly Poison V
	25902: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	25903: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	25911: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	25912: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	25913: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	25914: {DirectScale: 0.6789, DotScale: 0.6789, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Shock
	27605: {DirectScale: 0.8944, DotScale: 0.8944, DirectCoeff: 0.0, TickCoeff: 0.2},   // Shadow Word: Pain
	27618: {DirectScale: 0.9799, DotScale: 0.9799, DirectCoeff: 0.0, TickCoeff: 0.0},   // Blizzard
	27799: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	27800: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	27801: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	27803: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	27804: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	27805: {DirectScale: 0.9590, DotScale: 0.9590, DirectCoeff: 0.0, TickCoeff: 0.0},   // Holy Nova
	29228: {DirectScale: 0.5685, DotScale: 0.5500, DirectCoeff: 0.214, TickCoeff: 0.1}, // Flame Shock
	31016: {DirectScale: 0.9301, DotScale: 0.9301, DirectCoeff: 0.0, TickCoeff: 0.0},   // Eviscerate
}
