package core

import (
	"fmt"
	"strings"
)

// WoW Forever talent trees. Forever adds, removes and moves talents, so the classic
// per-class talent protos (which map a talent string by position) can't read a Forever
// talent string. Forever talents are parsed by name from the layouts in
// forever_talents_gen.go (generated by tools/forever/gen_talents.py), and each class maps
// them onto its engine talents plus Forever-only effects.

type ForeverTalent struct {
	Name     string
	Tier     int32
	MaxRank  int32
	Requires string
}

type ForeverTalentTree struct {
	Name    string
	Talents []ForeverTalent
}

// ForeverTalents holds a parsed Forever talent string: talent name -> rank.
type ForeverTalents map[string]int32

// Rank returns the points in a talent (0 if not taken). Panics on a name that isn't in
// any of the class's trees, so a typo in class code fails loudly in tests.
func (ft ForeverTalents) Rank(name string) int32 {
	r, ok := ft[name]
	if !ok {
		panic("unknown WoW Forever talent: " + name)
	}
	return r
}

func (ft ForeverTalents) Has(name string) bool {
	return ft.Rank(name) > 0
}

// ParseForeverTalents reads a "digits-digits-digits" talent string against the class's
// Forever trees. Every talent of the class is present in the result (rank 0 if untaken).
func ParseForeverTalents(trees [3]ForeverTalentTree, talents string) (ForeverTalents, error) {
	ft := ForeverTalents{}
	for _, tree := range trees {
		for _, t := range tree.Talents {
			ft[t.Name] = 0
		}
	}
	parts := strings.Split(talents, "-")
	if len(parts) > 3 {
		return nil, fmt.Errorf("talent string has %d trees", len(parts))
	}
	for i, part := range parts {
		tree := trees[i]
		if len(part) > len(tree.Talents) {
			return nil, fmt.Errorf("%s: %d talents given, tree has %d", tree.Name, len(part), len(tree.Talents))
		}
		spent := int32(0)
		for j, c := range part {
			if c < '0' || c > '9' {
				return nil, fmt.Errorf("%s: bad character %q", tree.Name, c)
			}
			rank := int32(c - '0')
			t := tree.Talents[j]
			if rank > t.MaxRank {
				return nil, fmt.Errorf("%s: %d points in %s (max %d)", tree.Name, rank, t.Name, t.MaxRank)
			}
			if rank > 0 && spent < (t.Tier-1)*5 {
				return nil, fmt.Errorf("%s: %s needs %d points in the tree first", tree.Name, t.Name, (t.Tier-1)*5)
			}
			if rank > 0 && t.Requires != "" && ft[t.Requires] == 0 {
				return nil, fmt.Errorf("%s: %s requires %s", tree.Name, t.Name, t.Requires)
			}
			ft[t.Name] = rank
			spent += rank
		}
	}
	return ft, nil
}

// ForeverTalentPoints is the total number of points in a parsed tree set.
func (ft ForeverTalents) Points() int32 {
	total := int32(0)
	for _, r := range ft {
		total += r
	}
	return total
}

// foreverPrimaryTree returns the index of the tree with the most points.
func foreverPrimaryTree(talents string) uint8 {
	best, bestPoints := 0, -1
	for i, part := range strings.Split(talents, "-") {
		points := 0
		for _, c := range part {
			points += int(c - '0')
		}
		if points > bestPoints {
			best, bestPoints = i, points
		}
	}
	return uint8(best)
}
