#!/usr/bin/env python3
"""Build the WoW Forever talent trees from the captured talent calculator text.

Input:  assets/db_inputs/forever/talents/raw/<class>.txt
        one talent per line, in calculator order (tree, then tier, then left to right):
        tree | tier | col | name | maxRank | requires | description
        Re-capture with tools/forever/fetch_forever_data.py when a new beta build ships.
Output: assets/db_inputs/forever/talents/<class>.json   (per class, with the build number)
        ui/core/forever/talents.json                     (all classes, for the web UI)
        sim/core/forever_talents_gen.go                  (tree layouts for the engine)

The talent string format is the classic one: one digit per talent in tree order,
trees separated by '-', trailing zeros may be dropped. Talents are identified by
position, so the order in the raw files must match the game's order.

Run from the repo root: python3 tools/forever/gen_talents.py
"""
import json
import os
import re

BUILD = '1.60.1.70170'
SOURCE = 'https://wow-forever.gg/talents/'
RAW = 'assets/db_inputs/forever/talents/raw/'
OUT = 'assets/db_inputs/forever/talents/'
CLASSES = {  # file -> proto class, expected talents per tree (0 = unknown)
    'warrior': 'ClassWarrior', 'paladin': 'ClassPaladin', 'hunter': 'ClassHunter',
    'rogue': 'ClassRogue', 'priest': 'ClassPriest', 'shaman': 'ClassShaman',
    'mage': 'ClassMage', 'warlock': 'ClassWarlock', 'druid': 'ClassDruid',
}


def per_rank(desc, max_rank):
    """Every a/b/c value series in the description that has exactly max_rank entries."""
    out = []
    for m in re.finditer(r'-?\d+(?:\.\d+)?(?:/-?\d+(?:\.\d+)?)+', desc):
        vals = [float(v) for v in m.group(0).split('/')]
        if len(vals) == max_rank:
            out.append(vals)
    return out


def load(cls):
    trees = []
    for line in open(RAW + cls + '.txt'):
        line = line.strip()
        if not line:
            continue
        tree, tier, col, name, max_rank, req, desc = [p.strip() for p in line.split('|', 6)]
        if not trees or trees[-1]['name'] != tree:
            trees.append({'name': tree, 'talents': []})
        max_rank = int(max_rank)
        trees[-1]['talents'].append({
            'name': name,
            'key': re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_'),
            'tier': int(tier),
            'col': None if col == '?' else int(col),
            'maxRank': max_rank,
            'requires': None if req == '-' else req,
            'description': desc,
            'perRank': per_rank(desc, max_rank) if max_rank > 1 else [],
        })
    assert len(trees) == 3, (cls, [t['name'] for t in trees])
    for t in trees:
        names = {x['name'] for x in t['talents']}
        for x in t['talents']:
            assert x['requires'] is None or x['requires'] in names, (cls, x['name'], x['requires'])
            assert x['maxRank'] <= 9, (cls, x['name'])
        tiers = [x['tier'] for x in t['talents']]
        assert tiers == sorted(tiers), (cls, t['name'], 'talents out of tier order')
    return trees


def go_string(s):
    return json.dumps(s)


def main():
    everything = {}
    go = [
        '// Code generated by tools/forever/gen_talents.py. DO NOT EDIT.',
        f'// WoW Forever talent trees, beta build {BUILD} ({SOURCE}).',
        '',
        'package core',
        '',
        'import "github.com/wowsims/sod/sim/core/proto"',
        '',
        f'const ForeverTalentsBuild = "{BUILD}"',
        '',
        'var ForeverTalentTrees = map[proto.Class][3]ForeverTalentTree{',
    ]
    for cls, pclass in CLASSES.items():
        trees = load(cls)
        doc = {'class': cls, 'build': BUILD, 'source': SOURCE + cls + '/', 'trees': trees}
        json.dump(doc, open(OUT + cls + '.json', 'w'), indent=1)
        everything[cls] = {'build': BUILD, 'trees': [
            {'name': t['name'], 'talents': [{k: x[k] for k in ('name', 'key', 'tier', 'maxRank', 'requires', 'description')} for x in t['talents']]}
            for t in trees]}
        go.append(f'\tproto.Class_{pclass}: {{')
        for t in trees:
            go.append(f'\t\t{{Name: {go_string(t["name"])}, Talents: []ForeverTalent{{')
            for x in t['talents']:
                req = go_string(x['requires'] or '')
                go.append(f'\t\t\t{{Name: {go_string(x["name"])}, Tier: {x["tier"]}, MaxRank: {x["maxRank"]}, Requires: {req}}},')
            go.append('\t\t}},')
        go.append('\t},')
        print(f'{cls:8s} ' + '  '.join(f'{t["name"]}: {len(t["talents"])} talents/{sum(x["maxRank"] for x in t["talents"])} ranks' for t in trees))
    go.append('}')
    os.makedirs('ui/core/forever', exist_ok=True)
    json.dump(everything, open('ui/core/forever/talents.json', 'w'), separators=(',', ':'))
    open('sim/core/forever_talents_gen.go', 'w').write('\n'.join(go) + '\n')


if __name__ == '__main__':
    main()
