#!/usr/bin/env python3
"""Generate spell-rank families (with learn levels) for WoW Forever leveling sims.

Source: assets/db_inputs/forever/spell_ranks.csv, extracted from the vanilla 1.12.1 spell
table (cmangos classic-db `spell_template`): every class spell's name, rank and learn level.
Spells the item database knows under a SoD-specific ID are added from its spell list.

Used by the engine to
  * let rotations fall back to the highest rank a character knows, and
  * pick the exact rank a character has at any level from tables measured at 25/40/50/60.

Run from the repo root: python3 tools/forever/gen_spell_ranks.py
Writes sim/core/forever_spell_ranks_gen.go
"""
import csv
import json

CLASS_FAMILIES = set(range(3, 12))  # mage..shaman spell families in the 1.12 spell table

families = {}
for row in csv.DictReader(open('assets/db_inputs/forever/spell_ranks.csv')):
    if int(row['spell_family']) not in CLASS_FAMILIES:
        continue
    key = (row['name'], int(row['spell_family']))
    families.setdefault(key, {})[int(row['id'])] = (int(row['rank']), int(row['spell_level']))

# Merge ranks the item database knows (some SoD/AQ rank IDs are missing from 1.12.1 data).
by_name = {}
for key in families:
    by_name.setdefault(key[0], []).append(key)
db = json.load(open('assets/database/db.json'))
for sp in db.get('spellIcons', []):
    if sp.get('rank', 0) > 0 and sp['name'] in by_name and len(by_name[sp['name']]) == 1:
        fam = families[by_name[sp['name']][0]]
        fam.setdefault(sp['id'], (sp['rank'], sp.get('requiresLevel', 60)))

# Engine-specific buff IDs that the 1.12 spell table doesn't group (no "Rank N" text),
# as {spellID: (rank, learn level)}.
EXTRA_FAMILIES = [
    {8515: (1, 32), 10609: (2, 42), 10612: (3, 52)},  # Windfury Totem buff (core.WindfuryBuffSpellId)
]
for i, fam in enumerate(EXTRA_FAMILIES):
    families[('__extra', i)] = fam

groups = []
for key in sorted(families):
    ranks = families[key]
    if len(ranks) < 2:
        continue
    groups.append(sorted(((r, lvl, sid) for sid, (r, lvl) in ranks.items()), reverse=True))

lines = [
    '// Code generated by tools/forever/gen_spell_ranks.py. DO NOT EDIT.',
    '',
    'package core',
    '',
    '// foreverSpellRanks lists each ranked class spell, highest rank first: {spellID, rank, learn level}.',
    'var foreverSpellRanks = [][][3]int32{',
]
for g in groups:
    lines.append('\t{' + ', '.join(f'{{{sid}, {r}, {lvl}}}' for r, lvl, sid in g) + '},')
lines += ['}', '']
open('sim/core/forever_spell_ranks_gen.go', 'w').write('\n'.join(lines))
print(len(groups), 'spell families')
