#!/usr/bin/env python3
"""Turn assets/db_inputs/forever/spell_tuning.csv into per-rank engine tuning.

Every rank of a tuned spell gets base damage scales of forever_max / classic_max (only the
max-rank values are public, so the ratio is applied to all ranks). Coefficient overrides are
applied to ranks learned at 20+, where Classic has no low-level coefficient penalty.

Run from the repo root: python3 tools/forever/gen_spell_tuning.py
Writes sim/core/forever_spell_tuning_gen.go
"""
import csv

FAMILY = {'mage': 3, 'warrior': 4, 'warlock': 5, 'priest': 6, 'druid': 7, 'rogue': 8, 'hunter': 9, 'paladin': 10, 'shaman': 11}

# Single-rank spells without a "Rank N" in the spell table.
SINGLE_RANK = {'Curse of Doom': 603}

ranks = {}
for row in csv.DictReader(open('assets/db_inputs/forever/spell_ranks.csv')):
    if int(row['spell_level']) > 0:
        ranks.setdefault((row['name'], int(row['spell_family'])), []).append((int(row['id']), int(row['spell_level'])))

spells = {}
lines = [l for l in open('assets/db_inputs/forever/spell_tuning.csv') if l.strip() and not l.startswith('#')]
for row in csv.DictReader(lines):
    key = (row['spell'], FAMILY[row['class']])
    t = spells.setdefault(key, {'direct': None, 'dot': None, 'direct_coeff': 0.0, 'tick_coeff': 0.0})
    scale = float(row['forever_max']) / float(row['classic_max'])
    t[row['part'] if row['part'] != 'all' else 'direct'] = scale
    if row['part'] == 'all':
        t['dot'] = scale
    if row['direct_coeff']:
        t['direct_coeff'] = float(row['direct_coeff'])
    if row['tick_coeff']:
        t['tick_coeff'] = float(row['tick_coeff'])

out = {}
missing = []
for key, t in spells.items():
    direct = t['direct'] if t['direct'] is not None else t['dot']
    dot = t['dot'] if t['dot'] is not None else t['direct']
    if key not in ranks and (key[0], 0) in ranks:
        key = (key[0], 0)  # some class spells carry no spell family in the 1.12 table
    if key not in ranks and key[0] in SINGLE_RANK:
        ranks[key] = [(SINGLE_RANK[key[0]], 60)]
    if key not in ranks:
        missing.append(key[0])
        continue
    for sid, level in ranks[key]:
        dc = t['direct_coeff'] if level >= 20 else 0
        tc = t['tick_coeff'] if level >= 20 else 0
        out[sid] = (direct, dot, dc, tc, key[0])

go = ['// Code generated by tools/forever/gen_spell_tuning.py. DO NOT EDIT.', '', 'package core', '',
      'var ForeverSpellTunings = map[int32]ForeverSpellTuning{']
for sid in sorted(out):
    d, p, dc, tc, name = out[sid]
    go.append(f'\t{sid}: {{DirectScale: {d:.4f}, DotScale: {p:.4f}, DirectCoeff: {dc}, TickCoeff: {tc}}}, // {name}')
go.append('}')
open('sim/core/forever_spell_tuning_gen.go', 'w').write('\n'.join(go) + '\n')
print(f'{len(spells)} spells -> {len(out)} ranks; not in spell table: {missing}')
